### ISSUE TITLE
How can i change processing to complete in order automatically

### ISSUE THREAD

**Issue by dolec** [PayU-EMEA/plugin_woocommerce#15]
Plugin does not change status? Is this normal?

**Comment by regdos** [comment]
Plugin changes order status automatically after receiving the notification from PayU.
When status is COPLETED plugin uses $order->payment_complete() method (https://github.com/PayU/plugin_woocommerce/blob/master/includes/class-woocommerce-payu.php#L204).
$order->payment_complete() comes from woo core and changes order status to processing or completed.
```$this->set_status( apply_filters( 'woocommerce_payment_complete_order_status', $this->needs_processing() ? 'processing' : 'completed', $this->get_id(), $this ) );```

More information about statuses: https://docs.woocommerce.com/document/managing-orders/

**Comment by Zjadlbymcos** [comment]
@dolec, are your website using cloudflare?

**Comment by mtrojanski** [comment]
Hi,

i have the same issue. After successful payment, payU redirect me to the shop, but the order status is ON-HOLD (in 90% cases). When i refresh page - everything is ok and status is PROCESSING. But... when i have devtools console opened - everything works fine. Weird. Another thing, when the payment was rejected, the order status (after redirect) is ON-HOLD. After refresh - status is changed to Cancelled.  Any ideas how to resolve these problems?

Wordpress: 5.4
Woocommerce: 4.0.1
PayU: 1.3.0

Im not using cloudflare.

**Comment by JurekSIN** [comment]
same issue here, it used to work but broke some months ago. We do use cloudflare, but in anycase, how would one go about troubleshooting this issue? 

Each order status we need to update manually in PayU, which takes about 30 minutes every day.

**Comment by JurekSIN** [comment]
Uwaga! Alleluja! Rozwiązanie dla uzytkownikow Cloudflare:

Dzień dobry,

Serwer Cloudflare którego Państwo używają blokuje nagłówki User-Agent=Jakarta - W odpowiedzi na wysłane notyfikacje serwer sklepu odpowiada błędem 403 (403: Forbidden/Zabroniony – serwer zrozumiał zapytanie, lecz konfiguracja bezpieczeństwa zabrania mu zwrócić żądany zasób)

Aby Państwa sklep zaczął odbierać notyfikacje z PayU, należy dodać do puli zaufanych adresów IP (w ustawieniach Cloudflare Firewall/Access Rules https://support.cloudflare.com/hc/en-us/articles/200170006-Do-I-need-to-whitelist-my-server-IPs-) adresy z których przesyłane są notyfikacje z PayU. Lista tych adresów IP to:

PRODUKCJA
185.68.12.10
185.68.12.11
185.68.12.12
185.68.12.26
185.68.12.27
185.68.12.28

Gdyby po rozpropagowaniu tej zmiany (np. za kilka godzin) nadal notyfikacja nie została doręczona, proszę skorzystać z dodatkowego sposobu tzn. ustawienia zezwolenia na żądania z nagłówkami User-Agent=Jakarta Commons-HttpClient/3.1 opisanego na: https://support.cloudflare.com/hc/en-us/articles/200170086-What-does-the-Browser-Integrity-Check-do-

W Panelu Managera PayU mogą Państwo zawsze sprawdzić jaka była odpowiedź na notyfikację do danej transakcji wchodząc w szczegóły transakcji, a następnie wybierając przycisk "Pokaż raporty". W tym samym miejscu można wybrać opcję "Ponów" aby notyfikacja została wysłana ponownie. 

Dla notyfikacji do transakcji zakończonej w czasie ostatnich 72 godzin nie jest konieczne ich ponowienie, ponieważ w przypadku niedoręczenia notyfikacji system PayU automatycznie ponawia próbę jej doręczenia dwudziestokrotnie zgodnie z tabelą podaną na http://developers.payu.com/pl/classic_api.html#classic_api_notifying_shop_about_change_transaction_status (dotyczy to zarówno Classic API jak i REST API).

**Comment by jackdanieIs** [comment]
Dzięki @JurekSIN to rozwiązało mój problem.
Can someone from PayU confirm the IP range? I just saw another IP that was blocked by my CF FW: 185.68.14.12

**Comment by regdos** [comment]
@jackdanieIs Możliwe adresy IP są dostępne na stronie [dokumentacji](https://developers.payu.com/pl/restapi.html#notifications).
