### ISSUE TITLE
Update internal OpenPayU library to the new version to suppress PHP 8 deprecation warning.  

### ISSUE THREAD

**Issue by blacksaildivision** [PayU-EMEA/plugin_woocommerce#28]
Using PHP8 following deprecation warning occurs: 
```PHP
Deprecated: Required parameter $outputFields follows optional parameter $namespace in /var/www/wp-content/plugins/woo-payu-payment-gateway/includes/lib/OpenPayU/Util.php on line 213
```
The problem has been fixed in the https://github.com/PayU-EMEA/openpayu_php repository ( https://github.com/PayU-EMEA/openpayu_php/issues/115 ) but it looks like this WordPress plugin uses an outdated version of OpenPayU library. Any chance for the update?

**Comment by regdos** [comment]
Version 2 of the plugin has an updated version of OpenPayU library
