### ISSUE TITLE
Zmiana statusu na zrealizowane

### ISSUE THREAD

**Issue by mateuszhublewski** [PayU-EMEA/plugin_woocommerce#32]
Cześć,

Czemu wtyczka nie zmienia statusu na "Zrealizowane" kiedy mamy sukces płatności?

Pozdrawiam

**Comment by mateuszhublewski** [comment]
Bump :)

**Comment by mateuszhublewski** [comment]
@regdos - bardzo proszę o pomoc, jutro uruchamiam sklep i muszę ręcznie zmieniać statusy :(

**Comment by regdos** [comment]
Czy sklep jest dostępny pod publicznym adresem?
Czy adres odbioru notyfikacji w sklepie nie jest zablokowany np. sklep wyłączony, itp.?

Proszę sprawdzić w panelu PayU "Historię raportów" dla jakiejkolwiek transakcji.

**Comment by mateuszhublewski** [comment]
@regdos dzięki za odp. Sklep jest publiczny, payu płatności przechodzą i jest status "zakończona" a w sklepie dalej "on-hold". Poradziłem sobie tymczasowo kupując wtyczkę za 150 zł na jakiejś stronie, ale trochę bez sensu wydatek jak to powinno działać w oficjalnym wydaniu...:(

**Comment by regdos** [comment]
Automatyczna zmiana statusów działa w oficjalnym wydaniu.  U Pana trzeba znaleźć przyczynę dlaczego tak się nie dzieje. Trzeba spojrzeć w historię raportów to tam widać jaka odpowiedź otrzymało PayU po wysłaniu notyfikacji do sklepu.

**Comment by tp-machura** [comment]
Witam,
Mam identyczny problem. 
Gdzie dokładnie znajdę historię raportów ?

**Comment by regdos** [comment]
@tp-machura 
To niepoprawna konfiguracja CloudFlare.

Proszę spojrzeć w zgłoszenie np. https://github.com/PayU-EMEA/plugin_prestashop/issues/274
