### ISSUE TITLE
Błąd po włączeniu opcji PayU - Blik

### ISSUE THREAD

**Issue by KamilCichon** [PayU-EMEA/plugin_woocommerce#36]
Błąd po włączeniu opcji PayU - Blik
Błąd powoduje wysypanie się całej strony (https://8-30.pl). Jeżeli wyłączę opcję PayU - Blik, wszystko wraca do normalności.

Fatal error: Uncaught Error: Call to a member function get_total() on null in /home/osma30/ftp/830/wp-content/plugins/woo-payu-payment-gateway/includes/WC_PayUGateways.php:872 Stack trace: #0 /home/osma30/ftp/830/wp-content/plugins/woo-payu-payment-gateway/includes/WC_PayUGateways.php(586): WC_PayUGateways->check_min_max(Object(stdClass), 'blik') #1 /home/osma30/ftp/830/wp-content/plugins/woo-payu-payment-gateway/includes/WC_Gateway_PayuBlik.php(32): WC_PayUGateways->process_pay_methods(Array) #2 /home/osma30/ftp/830/wp-content/plugins/woo-payu-payment-gateway/includes/WC_Gateway_PayuBlik.php(16): WC_Gateway_PayuBlik->try_retrieve_banks() #3 /home/osma30/ftp/830/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(97): WC_Gateway_PayuBlik->__construct() #4 /home/osma30/ftp/830/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(70): WC_Payment_Gateways->init() #5 /home/osma30/ftp/830/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(43): WC_Payment_Gateways->__constru in /home/osma30/ftp/830/wp-content/plugins/woo-payu-payment-gateway/includes/WC_PayUGateways.php on line 872

**Comment by regdos** [comment]
@KamilCichon problem dotyczy każdej strony np. listy produktów, szczegółów produktu czy tylko procesu zamawiania?
Jakie pluginy związane z WooCommerce ma Pan zainstalowane?

**Comment by regdos** [comment]
Naprawione w wersji 2.0.8
