### ISSUE TITLE
Wtyczka Elementor nie ładuje się - wersja 2.07 i 2.08

### ISSUE THREAD

**Issue by ncharzynska** [PayU-EMEA/plugin_woocommerce#37]
Niestety edycja w Elementorze nie ładuje się od momentu aktualizacji wtyczki do wersji 2.07 oraz do wersji 2.08. Dopiero rollback do 2.0.5 naprawia problem. Wtyczka powoduje, że w konsoli widać błąd 500 i przez to edytor nie ładuje się.
Dodatkowo w logach WooCommerce pojawiło się mnóstwo błędów krytycznych:

```
2021-07-20T01:33:19+00:00 CRITICAL Uncaught Error: Call to a member function get_total() on null in /home/charzyn/domains/charzynska.pl/public_html/wp-content/plugins/woo-payu-payment-gateway/includes/WC_PayUGateways.php:872
Stack trace:
#0 /home/charzyn/domains/charzynska.pl/public_html/wp-content/plugins/woo-payu-payment-gateway/includes/WC_PayUGateways.php(586): WC_PayUGateways->check_min_max(Object(stdClass), 'c')
#1 /home/charzyn/domains/charzynska.pl/public_html/wp-content/plugins/woo-payu-payment-gateway/includes/WC_Gateway_PayuSecureForm.php(61): WC_PayUGateways->process_pay_methods(Array)
#2 /home/charzyn/domains/charzynska.pl/public_html/wp-content/plugins/woo-payu-payment-gateway/includes/WC_Gateway_PayuSecureForm.php(20): WC_Gateway_PayuSecureForm->try_retrieve_banks()
#3 /home/charzyn/domains/charzynska.pl/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(97): WC_Gateway_PayuSecureForm->__construct()
#4 /home/charzyn/domains/charzynska.pl/public_html/wp-content/plugins/woocommerce/includes/class-wc- w /home/charzyn/domains/charzynska.pl/public_html/wp-content/plugins/woo-payu-payment-gateway/includes/WC_PayUGateways.php w linii 872

``` 

@regdos

**Comment by sebastiankorybski** [comment]
Cześć, potwierdzam problem z Elementorem, rozwala także G Site Kit (REST API). Połączenie REST API zwróciło następujący nieoczekiwany rezultat: (500) <br /> <b>Fatal error</b>: Uncaught Error: Call to a member function get_total() on null in .../public_html/wp-content/plugins/woo-payu-payment-gateway/includes/WC_PayUGateways.php:872 Stack trace: #0

**Comment by regdos** [comment]
@ncharzynska, @sebastiankorybski Proszę o test zmiany 
https://github.com/PayU-EMEA/plugin_woocommerce/commit/4aa63682079084f7d39db60d9d86e62f472248e3

tj. podmiane tego jednego zmienionego pliku.

**Comment by sebastiankorybski** [comment]
Wszystko działa poprawnie. Dzięki @regdos
