### ISSUE TITLE
Bug in /wp-json/wp/v2/post_type/_Post_id?_fields=title

### ISSUE THREAD

**Issue by przmkk** [PayU-EMEA/plugin_woocommerce#38]
v2.0.7

`PHP Fatal error: Uncaught Error: Call to a member function get_total() on null in /public_html/wp-content/plugins/woo-payu-payment-gateway/includes/WC_PayUGateways.php:872
Stack trace:
#0 /public_html/wp-content/plugins/woo-payu-payment-gateway/includes/WC_PayUGateways.php(586): WC_PayUGateways->check_min_max(Object(stdClass), ‘ai’)
#1 public_html/wp-content/plugins/woo-payu-payment-gateway/includes/WC_Gateway_PayuInstallments.php(29): WC_PayUGateways->process_pay_methods(Array)
#2 /wp-content/plugins/woo-payu-payment-gateway/includes/WC_Gateway_PayuInstallments.php(13): WC_Gateway_PayuInstallments->try_retrieve_banks()
#3 /public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(97): WC_Gateway_PayuInstallments->__construct()
#4 /public_html/wp-content/plugins/woo-payu-payment-gateway/includes/WC_PayUGateways.php on line 872 `

**Comment by regdos** [comment]
@przmkk 
Proszę o aktualziację do wersji 2.0.8 zostało to już naprawione.
