### ISSUE TITLE
Ponawianie płatności payU - brak możliwości zapłacenia przez payu. możliwa tylko  przy odbiorze.

### ISSUE THREAD

**Issue by deveropl** [PayU-EMEA/plugin_woocommerce#39]
Mam problem z ponawianiem płatności w woocommerce
W konfiguracji Payu wyłączyłem autoodbiór.
w mailu i na koncie użytkownika jest link z możliwością dokonania płatności ale po kliknięciu pojawia się komunikat:

Przykro nam, ale dla Twojej lokalizacji nie jest udostępniona żadna metoda płatności. Prosimy skontaktuj się z nami, jeśli potrzebujesz wyjaśnień lub chcesz omówić alternatywne sposoby płatności.

![Zrzut ekranu 2021-09-10 102432](https://user-images.githubusercontent.com/81684886/132824387-be407ec3-0be9-4536-8e14-8bf7a459ddbe.png)

Co robię  źle?

**Comment by deveropl** [comment]
ktoś miał podobny problem?  Wordpress 5.8.1 Woo 5.6.0

**Comment by regdos** [comment]
@deveropl Czy w parametrze "Włącz dla metod wysyłki" coś jest wybrane?

**Comment by deveropl** [comment]
Dziękuję za zainteresowanie moim problemem,
Tak. wszystko jest skonfigurowane poprawnie. W konfiguracji Payu wyłączyłem autoodbiór. podczas składania zamówień wszystko działa można płacić payu, można wybierać sposoby dostawy. Problem pojawia się gdy płatność Payu się nie powiedzie i klient klika w link (ponów płatność) przenosi go na stronę woocommerce gdzie znika możliwość wybrania PAYU. testowałem z opcją zwykłego przelewu bankowego i działało wszystko tak jak trzeba. problem jest tylko z wtyczką PAYU.

![Zrzut ekranu 2021-09-13 095438](https://user-images.githubusercontent.com/81684886/133046060-597009cf-4cf5-4e9c-af6a-1e3956544fa7.png)

![Zrzut ekranu 2021-09-13 095501](https://user-images.githubusercontent.com/81684886/133046155-7c2f21d3-8d1e-4fee-bc3d-215225aa9d0d.png)

**Comment by regdos** [comment]
Dziękują za info o konfiguracji. Będziemy sprawdzać.

**Comment by deveropl** [comment]
Właśnie w tym jest problem. że gdy klient próbuje ponowić płatność, znika mu możliwość wybrania sposobu dostawy i płatności.....
Podczas składania zamówienia wybieram sposób dostawy "Kurier przedpłata". sposób płatności "PAYU". gdy płatność się nie powiedzie i  klikam w link PONÓW płatność. pojawia się komunikat taki jak na pierwszym screenie.

**Comment by deveropl** [comment]
Sprawdziłem jeszcze raz. sposób dostawy jest prawidłowy:
![Zrzut ekranu 2021-09-13 145324](https://user-images.githubusercontent.com/81684886/133086995-a3751fbb-1d0d-4e42-999e-3fb9bb66b1fa.png)

po kliknięciu opłać zamówienie pojawia się "błędna metoda płatności"

![Zrzut ekranu 2021-09-13 145445](https://user-images.githubusercontent.com/81684886/133087233-0d1a6928-f3e7-467c-9b54-2a4eb5b66495.png)

poniżej link:
https://www.leyden.pl/zamowienie/order-pay/847735/?pay_for_order=true&key=wc_order_34kM6LAF1h5gp

**Comment by regdos** [comment]
Też sprawdziłem jest tak samo jak u Pana. Nie udało mi się tego powtórzyć u siebie. Jeżeli chciałby Pan żeby dalej spróbować to naprawić to potrzebujemy namiarów na stronę (ftp, panel) - proszę o kontakt ze wsparciem PayU z powołaniem się na to zgłoszenie wtedy korespondencja zostanie przekazana do mnie.

**Comment by deveropl** [comment]
Aktualizacja wtyczki PAYU 2.0.10 rozwiązała sprawę. Dziękuję za pomoc.
