### ISSUE TITLE
Pokazanie PayPo jako sposobu płatności

### ISSUE THREAD

**Issue by adrianratajczak** [PayU-EMEA/plugin_woocommerce#45]
Otrzymałem od PayPo informację, że w obecnym pluginie wystarczy dopisać tylko odpowiedni kod z wartością dla PayPo - dpp
Przeglądając dokumentację [restapi](https://developers.payu.com/pl/restapi.html#transparent) nie widzę żadnej wzmianki ani informacji gdzie tego szukać. 

Czy jest to w ogóle możliwe? W pluginie nie widzę żadnych assetów związanych z PayPo

**Comment by regdos** [comment]
W wersji 2.0.13 pluginu jest możliwość użycia PayPo jako osobnej metody płatności.
